"""add status to shipment event

Revision ID: 6a00385a5d25
Revises: aa4e085e68cd
Create Date: 2026-05-03 09:28:09.511074

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a00385a5d25'
down_revision: Union[str, Sequence[str], None] = 'aa4e085e68cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ShipmentEvent', sa.Column('status', sa.Enum('placed', 'shipped', 'in_transit', 'delivered', 'returned', name='shipmentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ShipmentEvent', 'status')
    # ### end Alembic commands ###
