"""add delivery partner

Revision ID: 7f7051746b0e
Revises: e631a51dfd79
Create Date: 2026-04-28 09:18:03.125731

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f7051746b0e'
down_revision: Union[str, Sequence[str], None] = 'e631a51dfd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverypartner',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('servicable_zip_codes', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('max_handling_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('seller', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('delivery_partner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'shipment', 'deliverypartner', ['delivery_partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'delivery_partner_id')
    op.drop_column('shipment', 'updated_at')
    op.drop_column('seller', 'updated_at')
    op.drop_table('deliverypartner')
    # ### end Alembic commands ###
