"""table change name

Revision ID: b45154da9f6d
Revises: 2ee30c18d903
Create Date: 2026-05-01 20:32:14.734369

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b45154da9f6d'
down_revision: Union[str, Sequence[str], None] = '2ee30c18d903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliverypartner')
    op.drop_constraint(op.f('shipment_delivery_partner_id_fkey'), 'shipment', type_='foreignkey')
    op.create_foreign_key(None, 'shipment', 'DeliveryPartner', ['delivery_partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_delivery_partner_id_fkey'), 'shipment', 'deliverypartner', ['delivery_partner_id'], ['id'])
    op.create_table('deliverypartner',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('servicable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('max_handling_capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('deliverypartner_pkey'))
    )
    # ### end Alembic commands ###
